### ISSUE TITLE
`.config.js` causes crash

### ISSUE THREAD

**Issue by Jason3S** [cosmiconfig/cosmiconfig#299]
Having a `.config.js` causes issues.

**`.config.js`**

```js
module.exports = {
    build: {},
    gateways: {},
    providers: {},
};
```

```
Error: No loader specified for extension ".yaml", so searchPlaces item "cspell.config.yaml" is invalid
    at /Users/jason/.nvm/versions/node/v16.18.1/lib/node_modules/cspell/node_modules/cosmiconfig/dist/ExplorerBase.js:52:15
    at Array.forEach (<anonymous>)
    at Explorer.validateConfig (/Users/jason/.nvm/versions/node/v16.18.1/lib/node_modules/cspell/node_modules/cosmiconfig/dist/ExplorerBase.js:47:25)
    at new ExplorerBase (/Users/jason/.nvm/versions/node/v16.18.1/lib/node_modules/cspell/node_modules/cosmiconfig/dist/ExplorerBase.js:25:10)
    at new Explorer (/Users/jason/.nvm/versions/node/v16.18.1/lib/node_modules/cspell/node_modules/cosmiconfig/dist/Explorer.js:22:5)
    at cosmiconfig (/Users/jason/.nvm/versions/node/v16.18.1/lib/node_modules/cspell/node_modules/cosmiconfig/dist/index.js:84:20)
```

Related to #296

**Comment by d-fischer** [comment]
Not quite related. Also I intended the `mergeLoaders` parameters to be for something else, but at second though, it might make sense to do it differently (later). Will close your PR and remove that parameter.
