### ISSUE TITLE
`explorer.search(...)` crashes with `{stopDir: undefined}` option

### ISSUE THREAD

**Issue by dotboris** [cosmiconfig/cosmiconfig#317]
The following code generates a crash:

```js
const explorer = cosmiconfig('testing', { stopDir: undefined })
const res = await explorer.search('.')
```

The full error message is:
```js
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1101:7)
    at Explorer.search (/home/dotboris/code/cosmiconfig/dist/Explorer.js:36:45)
    at file:///home/dotboris/code/cosmiconfig/__scratch/main.mjs:5:30
    at file:///home/dotboris/code/cosmiconfig/__scratch/main.mjs:7:3
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

This used to work in `v8.2.0` but seems to be broken in `v8.3.0`. I've done some bisecting and it the first commit that causes this is 39207b6357568b1568203e0c8e0ae3a40d6d77bc

For some context, I stumbled on this issue in the context of `stylelint`. Example of the failure: https://github.com/dotboris/prod-guard/actions/runs/6059403893/job/16442488539?pr=983

**Comment by dotboris** [comment]
I've done some more digging an the source of this issue is a little deeper than https://github.com/cosmiconfig/cosmiconfig/commit/39207b6357568b1568203e0c8e0ae3a40d6d77bc. While that commit triggers the crash, there's a deeper issue here around how default options are handled.

`stylelint` passes `stopDir: undefined` which from what I understand is meant to indicate "use the default value" but because of the way JS object merging (`{ ...default, ...options }`) behave, that's not what happens.

This is what happens:
```js
> { ...({stopDir: 'default'}), ...({stopDir: undefined}) }
{ stopDir: undefined }
```

For reference, here's the option merging code:

```ts
function normalizeOptions(
  moduleName: string,
  options: Readonly<Options>,
): InternalOptions {
  const defaults = {
    packageProp: moduleName,
    searchPlaces: [
      // ... snip ...
    ],
    ignoreEmptySearchPlaces: true,
    stopDir: os.homedir(),
    cache: true,
    transform: identity,
    loaders: defaultLoaders,
    metaConfigFilePath: null,
  };

  const normalizedOptions = {
    ...defaults,
    ...options,
    loaders: {
      ...defaults.loaders,
      ...options.loaders,
    },
  };

  return normalizedOptions;
}
```

**Comment by dotboris** [comment]
What's interesting and odd here is that I would expect TypeScript to catch this but it doesn't. Here's a minimal example:

```ts
interface Options {
  stuff?: string
}

const options: Options = { stuff: undefined }
const d: Required<Options> = {
  stuff: 'default'
}
const merged = { ...d, ...options }
console.log(merged)
```

The type of `merged` is
```ts
const merged: {
    stuff: string;
}
```

But when you run it, it outputs `{ stuff: undefined }`

This is more of a fun fact / separate rabbit hole but I don't think that it's super relevant to this issue here.
