### ISSUE TITLE
Error: EACCES: permission denied, open '/.config/puppeteerrc’

### ISSUE THREAD

**Issue by caraxlr** [cosmiconfig/cosmiconfig#332]
Hi, I encountered this error while trying to run [kibana](https://www.elastic.co/guide/en/kibana/current/introduction.html). To reproduce this error, I ran:
```
cd /home/phoebus3/XIAOL/test/elk-deployment/C2/test
curl -O https://artifacts.elastic.co/downloads/kibana/kibana-8.10.3-linux-x86_64.tar.gz
curl https://artifacts.elastic.co/downloads/kibana/kibana-8.10.3-linux-x86_64.tar.gz.sha512 | shasum -a 512 -c - 
tar -xzf kibana-8.10.3-linux-x86_64.tar.gz
/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/bin/kibana
```
And I found that some people experienced similar issues, and this bug may come from this package? So hopefully you can have a look on it?
https://github.com/puppeteer/puppeteer/issues/11076
https://github.com/elastic/kibana/issues/165632

I don't have the root authority. So maybe it's the problem. Thanks!

**Comment by d-fischer** [comment]
I can not reproduce this by running Kibana, even if running outside of the home directory (which I suspect might be a problem). The test code in the Puppeteer issue is also not reproducible. I'm gonna need *some* setup that can reproduce this issue to fix it.

**Comment by caraxlr** [comment]
Hi Daniel, thank you for helping out! I think this error may be related to the permission of /.config? I don't have any permission for it. Thanks again!
`(base) bash-4.4$ ls -ld /.config
drwx------ 3 root root 19 Aug 16 17:04 /.config
`

**Comment by caraxlr** [comment]
Here is the stack trace of the error:

[2023-10-20T12:13:10.548-05:00][FATAL][root] Reason: EACCES: permission denied, open '/.config/puppeteerrc'
Error: EACCES: permission denied, open '/.config/puppeteerrc'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at ExplorerSync.#readConfiguration (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:76:39)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:44:63)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/util.js:12:20)
    at ExplorerSync.search (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/cosmiconfig/dist/ExplorerSync.js:71:42)
    at getConfiguration (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/puppeteer/lib/cjs/puppeteer/getConfiguration.js:38:68)
    at Object.<anonymous> (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js:36:66)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/@kbn/screenshotting-plugin/server/browsers/chromium/driver.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at Module.Hook._require.Module.require (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/require-in-the-middle/index.js:188:39)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/phoebus3/XIAOL/test/elk-deployment/C2/test/kibana-8.10.3/node_modules/@kbn/screenshotting-plugin/server/browsers/chromium/index.js:32:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

 FATAL  Error: EACCES: permission denied, open '/.config/puppeteerrc'

Thanks again!

**Comment by caraxlr** [comment]
Thanks a lot!

**Comment by MrsSima** [comment]
Hmm still happening on v9.0 with me
140.7 npm ERR! node:fs:1596
140.7 npm ERR!   handleErrorFromBinding(ctx);
140.7 npm ERR!   ^
140.7 npm ERR! 
140.7 npm ERR! Error: EACCES: permission denied, stat '/root/.config/puppeteer'
140.7 npm ERR!     at Object.statSync (node:fs:1596:3)
140.7 npm ERR!     at isDirectorySync (/home/node/node_modules/puppeteer/node_modules/cosmiconfig/dist/util.js:88:35)
140.7 npm ERR!     at search (/home/node/node_modules/puppeteer/node_modules/cosmiconfig/dist/ExplorerSync.js:47:47)

**Comment by d-fischer** [comment]
That is something different - this looks in your own home directory, so your permissions are actually broken. I'll put in a workaround when I can, but this is mostly an issue of your system.

**Comment by nilijev** [comment]
check: https://github.com/puppeteer/puppeteer/issues/11076#issuecomment-1980581683

**Comment by brandonsoccer22** [comment]
@MrsSima I encountered a similar issue as you when running my Node/Puppeteer script with [Supervisor](http://supervisord.org/). I had the right user specified, but I had to also specify the home directory in the [subprocess environment](http://supervisord.org/subprocess.html#subprocess-environment) with `environment=HOME="/home/queue-worker"`

I would check the output of following to see if you are experiencing a similar issue (assuming you do not want `/root` to be the home directory):

```
const { default: os } = await import("os");
console.log('User: ' + process.env.USER);
console.log('HOME: ' + process.env.HOME);
console.log(os.homedir())
```
For people not using Supervisor, a more general fix might be [setting environment variables](https://www.sitepoint.com/node-js-environment-variables-how-to-set-them-properly/), maybe something like `export HOME=/home/queue-worker && node your_script.js`. Hope that helps!

**Comment by yasserhussien** [comment]
> That is something different - this looks in your own home directory, so your permissions are actually broken. I'll put in a workaround when I can, but this is mostly an issue of your system.

Hi @d-fischer if it is an issue from my own system how to fix it?
I have the same issue
Error: EACCES: permission denied, open '/.config/puppeteerrc'
    at Object.openSync (node:fs:591:3)
    at Object.readFileSync (node:fs:459:35)
    at #readConfiguration (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:76:39)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:44:63)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50)
    at emplace (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/util.js:12:20)
    at search (/var/tmp/vproj/pvid/node_modules/cosmiconfig/dist/ExplorerSync.js:64:50) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/.config/puppeteerrc'
}

### Puppeteer version

23.0.2

### Node version

20.15.0

### Package manager

npm

### Package manager version

10.8.2

**Comment by grinapo** [comment]
Would have been nice to know **which commit have fixed this** (or how) since I cannot control which version a package pulls in through bazillions of interdependencies.

**Comment by grinapo** [comment]
It was my fast path very stylish to change in `node_modules/cosmiconfig/dist/readFile.js` to directly override filepath in `readFileSync` as
`filepath = "/home/user/" + filepath`
I wish there was a proper changeset.

**Comment by supun-io** [comment]
I had the exact issue while running Puppeteer via Supervisor. @brandonsoccer22's [answer](https://github.com/cosmiconfig/cosmiconfig/issues/332#issuecomment-2040290618) worked perfectly.

**Comment by Dunedubby** [comment]
I was wondering if it might make sense to change the default behavior so that EACCES/permission problems are dealt with silently or with just a warning. As it stands, a project must have permissions for every parent folder until it hits $HOME, but this seems like a lot to ask for cases where there are lots of environments or symlinks. Modularity-wise, it seems better to have the ability to place a project anywhere you'd like, and still have it run without having to change $HOME to be a non-home folder just so that it doesn't trace every possible config file all the way up the chain. Just my opinion though.

**Comment by Dunedubby** [comment]
@d-fischer I was wondering if it might make sense to change the default behavior so that EACCES/permission problems are dealt with silently or with just a warning. As it stands, a project must have permissions for every parent folder until it hits $HOME, but this seems like a lot to ask for cases where there are lots of environments or symlinks. Modularity-wise, it seems better to have the ability to place a project anywhere you'd like, and still have it run without having to change $HOME to be a non-home folder just so that it doesn't trace every possible config file all the way up the chain. Just my opinion though.
